modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Artur114Projects/Armored_Arms/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/armored-arms"
authors="${mod_authors}"
description='''${mod_description}'''